# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate Static Files & Deploy

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: 0 */2 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run
      env:
        AM_CLIENT_ID: ${{ secrets.AM_CLIENT_ID }}
        AM_CLIENT_SECRET: ${{ secrets.AM_CLIENT_SECRET }}
        AM_LIST: jokin1999/quic-search/2/1;2dust/v2rayN/5/1;nilaoda/N_m3u8DL-CLI/2/1;ColaSign/haidan;alecthw/mmdb_china_ip_list/5/1;
      run: |
        python main.py

    - name: Build
      run: php ./src/tool.php

#     - name: Clean
#       uses: dawidd6/action-delete-branch@v3
#       with:
#         branches: vercel

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: vercel
        FOLDER: public
