# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate Static Files & Deploy

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: 0 */2 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run
      env:
        AM_CLIENT_ID: ${{ secrets.AM_CLIENT_ID }}
        AM_CLIENT_SECRET: ${{ secrets.AM_CLIENT_SECRET }}
        AM_LIST: jokin1999/quic-search/2/1;2dust/v2rayN/5/1;nilaoda/N_m3u8DL-CLI/2/1;ColaSign/haidan;alecthw/mmdb_china_ip_list/1/1;
      run: |
        python main.py

    - name: Build
      run: php ./src/tool.php
      env:
        FB_DIR: ${{ secrets.FB_DIR }}
        FB_EXCEPT: ${{ secrets.FB_EXCEPT }}
        FB_TPL_PATH: ${{ secrets.FB_TPL_PATH }}
        FB_REMOTE_TPL_ALLOW: ${{ secrets.FB_REMOTE_TPL_ALLOW }}
        FB_REMOTE_TPL_PATH: ${{ secrets.FB_REMOTE_TPL_PATH }}
        FB_CDN_REMOTE_TPL_PATH: ${{ secrets.FB_CDN_REMOTE_TPL_PATH }}
        FB_REMOTE_TPL_PATH_FORCE: ${{ secrets.FB_REMOTE_TPL_PATH_FORCE }}
        FB_STATIC_FILE: ${{ secrets.FB_STATIC_FILE }}
        FB_TITLE: ${{ secrets.FB_TITLE }}
        FB_SUBTITLE_LINK: ${{ secrets.FB_SUBTITLE_LINK }}
        FB_SUBTITLE_TEXT: ${{ secrets.FB_SUBTITLE_TEXT }}
        FB_AKM_LINK: ${{ secrets.FB_AKM_LINK }}
        FB_AKM_TEXT: ${{ secrets.FB_AKM_TEXT }}
        FB_CDN_JSDELIVR: ${{ secrets.FB_CDN_JSDELIVR }}
        FB_VIDEO_DONWLOAD_BTN: ${{ secrets.FB_VIDEO_DONWLOAD_BTN }}
        FB_AUDIO_DONWLOAD_BTN: ${{ secrets.FB_AUDIO_DONWLOAD_BTN }}
        FB_COMPRESS: ${{ secrets.FB_COMPRESS }}
        FB_CORE_REPO: ${{ github.repository }}
        FB_CDN_JSDELIVR_VERSION: ${{ secrets.FB_CDN_JSDELIVR_VERSION}}

#     - name: Clean
#       uses: dawidd6/action-delete-branch@v3
#       with:
#         branches: vercel

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: pages_vercel
        FOLDER: public
